import { ICharacter } from './interfaces'

export const charactersArray: ICharacter[] = [
  { symbol: '`' },
  { symbol: '1' },
  { symbol: '2' },
  { symbol: '3' },
  { symbol: '4' },
  { symbol: '5' },
  { symbol: '6' },
  { symbol: '7' },
  { symbol: '8' },
  { symbol: '9' },
  { symbol: '0' },
  { symbol: '-' },
  { symbol: '=' },
  { symbol: '←', width: 158 },
  { symbol: 'tab', width: 115 },
  { symbol: 'q' },
  { symbol: 'w' },
  { symbol: 'e' },
  { symbol: 'r' },
  { symbol: 't' },
  { symbol: 'y' },
  { symbol: 'u' },
  { symbol: 'i' },
  { symbol: 'o' },
  { symbol: 'p' },
  { symbol: '[' },
  { symbol: ']' },
  { symbol: '|', width: 93 },
  { symbol: 'caps', width: 130 },
  { symbol: 'a' },
  { symbol: 's' },
  { symbol: 'd' },
  { symbol: 'f' },
  { symbol: 'g' },
  { symbol: 'h' },
  { symbol: 'j' },
  { symbol: 'k' },
  { symbol: 'l' },
  { symbol: ';' },
  { symbol: '"' },
  { symbol: 'enter', width: 134 },
  { symbol: 'shift', width: 160 },
  { symbol: 'z' },
  { symbol: 'x' },
  { symbol: 'c' },
  { symbol: 'v' },
  { symbol: 'b' },
  { symbol: 'n' },
  { symbol: 'm' },
  { symbol: ',' },
  { symbol: '.' },
  { symbol: '/' },
  { symbol: 'shift', width: 160 },
  { symbol: 'ctrl' },
  { symbol: 'win' },
  { symbol: 'alt' },
  { symbol: 'space', width: 300 },
  { symbol: 'alt' },
  { symbol: 'ctrl' },
]
